export const EngineeringResearch = [

  {
    id: 1,
    name: "Hyperloop",
    img: "/images/portfolio/train.jpg",
    text: "A hyperloop train pod design by Cornell Hyperloop Project Team. ",
    hasLink: true,
    Link: "https://hyperloop.cornell.edu/",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 2,
    name: "Organic Robotics Lab",
    img: "/images/portfolio/peeler.jpg",
    text: "",
    hasLink: true,
    hasInternalLink: true,
    dest: "/CADcollection#start",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 3,
    name: "Water Pump",
    img: "/images/portfolio/peeler.jpg",
    text: "",
    hasLink: true,
    hasInternalLink: true,
    dest: "/CADcollection#WP",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 4,
    name: "Music Sheet Turner",
    img: "/images/portfolio/peeler.jpg",
    text: "",
    hasLink: true,
    hasInternalLink: true,
    dest: "/CADcollection#MST",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 5,
    name: "Reuleaux Machine",
    img: "/images/portfolio/peeler.jpg",
    text: "",
    hasLink: true,
    hasInternalLink: true,
    dest: "/CADcollection#RM",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 6,
    name: "Fruit Peeler",
    img: "/images/portfolio/peeler.jpg",
    text: "",
    hasLink: true,
    hasInternalLink: true,
    dest: "/CADcollection/#FP",
    color: "#58A5FF",
    font: "initial",
  },
]


export const GameWeb = [
  {
    id: 1,
    name: "Seven-Days",
    img: "/images/portfolio/seven_days.jpg",
    text: "Indie developed puzzle adventure game with great aesthetics. ",
    hasLink: true,
    Link: "https://uming.itch.io/",
    color: "white",
    font: "monospace",
  },

  {
    id: 2,
    name: "Ring Ithaca",
    img: "/images/portfolio/ring_ithaca.png",
    text: "Website for the Cornell Club Ring of Steel. ",
    hasLink: true,
    Link: "https://ring-of-steel-ithaca.netlify.app/",
    color: "white",
    font: "monospace",
  },
  {
    id: 3,
    name: "SomniPhobia",
    img: "/images/portfolio/somniphobia.JPG",
    text: "A puzzle platformer developed by a team of students at Cornell Game Design Initiative. ",
    hasLink: true,
    Link: "https://gdiac.cs.cornell.edu/showcase/gallery/somniphobia/",
    color: "white",
    font: "monospace",
  },
]


export const ArtOther = [
  {
    id: 8,
    name: "Art Collection",
    img: "/images/portfolio/arts.png",
    text: "",
    hasLink: true,
    Link: "https://www.deviantart.com/u--ming",
    color: "palevioletred",
    font: "Charmonman",
  },
  {
    id: 6,
    name: "Sword Design",
    img: "/images/portfolio/sword.jpg",
    text: "An aesthetic sword design, made with CAD, laser cutting, and 3D printing. ",
    hasInternalLink: true,
    dest: "/CADcollection/#FP",
    color: "palevioletred",
    font: "Charmonman",
  },
]