export const EngineeringResearch = [
  {
    id: 0,
    name: "Fluid System Design at SpaceX",
    img: "/images/portfolio/starship.jpg",
    text: "I worked on Starship Production and Testing. ",
    hasLink: true,
    Link: "https://www.spacex.com/launches/mission/?missionId=starship-flight-test",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 0,
    name: "Robots Competition",
    img: "/images/portfolio/mechatronics.jpg",
    text: "We built a robot to compete in a game of cube collecting. ",
    hasLink: false,
    Link: "",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 0,
    name: "Glider Design",
    img: "/images/portfolio/glider.jpg",
    text: "My team designed and built a glider capable of gliding >10 meters. ",
    hasLink: false,
    Link: "",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 0,
    name: "Fluid-Mechanical Dissection",
    img: "/images/portfolio/airfoil.jpg",
    text: "A video about how the strandbeest works. ",
    hasLink: true,
    Link: "https://www.youtube.com/watch?v=-GiVZtnf3kU&t=84s",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 1,
    name: "Hyperloop",
    img: "/images/portfolio/train.jpg",
    text: "We designed and built a hyperloop train pod from ground up and competed in Canadian Hyperloop Competition.",
    hasLink: true,
    Link: "https://hyperloop.cornell.edu/",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 2,
    name: "Organic Robotics Lab",
    img: "/images/portfolio/research.JPEG",
    text: "I was a research intern for a Traumatic Brain Injury (TBI) detection project in the Cornell Organic Robotics Lab.",
    hasLink: true,
    Link: "https://orl.mae.cornell.edu/index.html",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 3,
    name: "Water Pump",
    img: "/images/portfolio/pump.jpg",
    text: "A group project for the Mechanical Synthesis class. ",
    hasLink: true,
    hasInternalLink: true,
    dest: "/CADcollection#WP",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 4,
    name: "Music Sheet Turner",
    img: "/images/portfolio/ODP.png",
    text: "An Open Deisign Project for the Mechanical Synthesis class. ",
    hasLink: true,
    hasInternalLink: true,
    dest: "/CADcollection#MST",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 5,
    name: "Reuleaux Machine",
    img: "/images/portfolio/Reuleaux.jpg",
    text: "",
    hasLink: true,
    hasInternalLink: true,
    dest: "/CADcollection#RM",
    color: "#58A5FF",
    font: "initial",
  },
  {
    id: 6,
    name: "Fruit Peeler",
    img: "/images/portfolio/peeler.jpg",
    text: "",
    hasLink: true,
    hasInternalLink: true,
    dest: "/CADcollection/#FP",
    color: "#58A5FF",
    font: "initial",
  },
]


export const GameWeb = [
  {
    id: 1,
    name: "Seven-Days",
    img: "/images/portfolio/seven_days.jpg",
    text: "Indie developed puzzle adventure game with great aesthetics. ",
    hasLink: true,
    Link: "https://uming.itch.io/",
    color: "white",
    font: "monospace",
  },

  {
    id: 2,
    name: "Ring Ithaca",
    img: "/images/portfolio/ring_ithaca.png",
    text: "Website for the Cornell Club Ring of Steel. ",
    hasLink: true,
    Link: "https://ring-of-steel-ithaca.netlify.app/",
    color: "white",
    font: "monospace",
  },
  {
    id: 3,
    name: "SomniPhobia",
    img: "/images/portfolio/somniphobia.JPG",
    text: "A puzzle platformer developed at Cornell Game Design Initiative. ",
    hasLink: true,
    Link: "https://gdiac.cs.cornell.edu/temp/showcase/",
    color: "white",
    font: "monospace",
  },
]


export const ArtOther = [
  {
    id: 8,
    name: "Art Collection",
    img: "/images/portfolio/arts.png",
    text: "Paintings and drawings. ",
    hasLink: true,
    Link: "https://www.deviantart.com/u--ming",
    color: "palevioletred",
    font: "Charmonman",
  },
  {
    id: 6,
    name: "Sword Design",
    img: "/images/portfolio/sword.jpg",
    text: "Aesthetic sword design that mimics window art. ",
    hasLink: true,
    Link: "../../public/PDFs/sword_design.pdf",
    color: "palevioletred",
    font: "Charmonman",
  },
]